# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deleted_date',
            new_name='deleted_Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published_Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags_nameofblog',
            new_name='tags_Name_Of_Blog',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags_place',
            new_name='tags_Place',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags_season',
            new_name='tags_Season',
        ),
    ]
