# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160514_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted_Date',
        ),
    ]
