# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160514_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sate',
            new_name='state',
        ),
    ]
